@startuml
actor users
users -> semester : 选择学期
semester -> course :选择课程
course -> class: 根据选择的学期与课程查寻班级
class -> student: 按班级查找学生列表
alt 如果users是老师
	student -> grades
	grades -> tests
	tests --> users:每个学生的信息、及每个实验的成绩
else 如果users是students，或者未登录
    class --> users:每个学生的信息
end
@enduml